#!/usr/bin/env python3
"""
CHECKLOCKTIMEVERIFY Script Examples
Demonstrates the actual Bitcoin scripts generated by the plugin
"""

def hex_to_script_readable(script_hex):
    """Convert hex script to human-readable format"""
    from electrum.transaction import opcodes
    
    script_bytes = bytes.fromhex(script_hex)
    result = []
    i = 0
    
    while i < len(script_bytes):
        opcode = script_bytes[i]
        
        if opcode == 0:
            result.append("OP_0")
            i += 1
        elif opcode <= 75:  # Direct push
            length = opcode
            i += 1
            data = script_bytes[i:i+length]
            if length <= 4:
                # Try to interpret as number
                try:
                    num = int.from_bytes(data, 'little', signed=False)
                    result.append(f"PUSH {length} bytes: 0x{data.hex()} (= {num})")
                except:
                    result.append(f"PUSH {length} bytes: 0x{data.hex()}")
            else:
                result.append(f"PUSH {length} bytes: 0x{data.hex()[:32]}...")
            i += length
        elif opcode == opcodes.OP_PUSHDATA1:
            i += 1
            length = script_bytes[i]
            i += 1
            data = script_bytes[i:i+length]
            result.append(f"OP_PUSHDATA1 {length} bytes: 0x{data.hex()[:32]}...")
            i += length
        else:
            # Find opcode name
            opcode_name = None
            for name, value in vars(opcodes).items():
                if value == opcode and name.startswith('OP_'):
                    opcode_name = name
                    break
            result.append(opcode_name or f"OP_UNKNOWN(0x{opcode:02x})")
            i += 1
    
    return '\n'.join(result)


print("=" * 80)
print("CHECKLOCKTIMEVERIFY Script Examples")
print("=" * 80)
print()

# Example 1: Simple Timelock with Block Height
print("EXAMPLE 1: Simple Timelock (Block Height)")
print("-" * 80)
print()
print("Parameters:")
print("  Locktime: 900000 (block height)")
print("  Pubkey: 02" + "a" * 62 + " (example compressed pubkey)")
print()

locktime_900000 = "03a0bb0d"  # 900000 in little-endian, minimal encoding
pubkey_example = "02" + "a" * 62
simple_script = locktime_900000 + "b175" + "21" + pubkey_example + "ac"

print("Script (hex):")
print(f"  {simple_script}")
print()
print("Script (human-readable):")
print(hex_to_script_readable(simple_script))
print()
print("Byte-by-byte breakdown:")
print(f"  03       - PUSH 3 bytes")
print(f"  a0 bb 0d - Locktime 900000 in little-endian (0x0DBB80 → 80BB0D → a0bb0d after minimal encoding)")
print(f"  b1       - OP_CHECKLOCKTIMEVERIFY (0xb1 = 177)")
print(f"  75       - OP_DROP (0x75 = 117)")
print(f"  21       - PUSH 33 bytes")
print(f"  02aaa... - Public key (33 bytes, compressed)")
print(f"  ac       - OP_CHECKSIG (0xac = 172)")
print()

# Show stack execution
print("Stack execution when spending:")
print("  Initial:        <sig> <pubkey> <script>")
print("  Script pushes:  <sig> <pubkey> 900000")
print("  After CLTV:     <sig> <pubkey> 900000      ← Validates locktime!")
print("  After DROP:     <sig> <pubkey>")
print("  Push pubkey:    <sig> <pubkey> <pubkey>    ← From script")
print("  After CHECKSIG: <true/false>               ← Result")
print()
print("CHECKLOCKTIMEVERIFY validation:")
print("  ✓ Transaction nLockTime >= 900000")
print("  ✓ Both are block heights (< 500000000)")
print("  ✓ Input nSequence < 0xffffffff")
print()

# Example 2: Simple Timelock with Timestamp
print()
print("=" * 80)
print("EXAMPLE 2: Simple Timelock (Timestamp)")
print("-" * 80)
print()

timestamp = 1735689600  # 2025-01-01 00:00:00 UTC
timestamp_hex = timestamp.to_bytes(4, 'little').hex()
print("Parameters:")
print(f"  Locktime: {timestamp} (Unix timestamp = 2025-01-01 00:00:00 UTC)")
print(f"  Pubkey: 03" + "b" * 62)
print()

pubkey_example2 = "03" + "b" * 62
timestamp_script = "04" + timestamp_hex + "b175" + "21" + pubkey_example2 + "ac"

print("Script (hex):")
print(f"  {timestamp_script}")
print()
print("Byte-by-byte breakdown:")
print(f"  04             - PUSH 4 bytes")
print(f"  {timestamp_hex} - Timestamp {timestamp} in little-endian")
print(f"  b1             - OP_CHECKLOCKTIMEVERIFY")
print(f"  75             - OP_DROP")
print(f"  21             - PUSH 33 bytes")
print(f"  03bbb...       - Public key")
print(f"  ac             - OP_CHECKSIG")
print()
print("CHECKLOCKTIMEVERIFY validation:")
print(f"  ✓ Transaction nLockTime >= {timestamp}")
print("  ✓ Both are timestamps (>= 500000000)")
print("  ✓ Input nSequence < 0xffffffff")
print()

# Example 3: Escrow Script
print()
print("=" * 80)
print("EXAMPLE 3: Escrow with Timelock Fallback (BIP-65 Example)")
print("-" * 80)
print()
print("Parameters:")
print("  Locktime: 900000 (3 months in blocks, approx)")
print("  Party 1 (Alice): 02" + "11" * 31)
print("  Party 2 (Bob):   02" + "22" * 31)
print("  Escrow (Lenny):  02" + "33" * 31)
print()

party1 = "02" + "11" * 31
party2 = "02" + "22" * 31
escrow = "02" + "33" * 31

escrow_script = (
    "63"          # OP_IF
    + locktime_900000  # locktime
    + "b1"        # OP_CHECKLOCKTIMEVERIFY
    + "75"        # OP_DROP
    + "21" + escrow    # escrow pubkey
    + "ad"        # OP_CHECKSIGVERIFY
    + "51"        # OP_1 (need 1 more sig)
    + "67"        # OP_ELSE
    + "52"        # OP_2 (need 2 sigs)
    + "68"        # OP_ENDIF
    + "21" + party1    # party1 pubkey
    + "21" + party2    # party2 pubkey
    + "52"        # OP_2 (2 keys)
    + "ae"        # OP_CHECKMULTISIG
)

print("Script (hex):")
print(f"  {escrow_script}")
print()
print("Script (human-readable):")
print(hex_to_script_readable(escrow_script))
print()
print("Detailed breakdown:")
print()
print("IF Branch (after timeout):")
print("  63                   - OP_IF")
print("  03 a0bb0d            - PUSH locktime (900000)")
print("  b1                   - OP_CHECKLOCKTIMEVERIFY")
print("  75                   - OP_DROP")
print("  21 02333333...       - PUSH escrow pubkey")
print("  ad                   - OP_CHECKSIGVERIFY")
print("  51                   - OP_1 (need 1 more signature)")
print()
print("ELSE Branch (normal case):")
print("  67                   - OP_ELSE")
print("  52                   - OP_2 (need 2 signatures)")
print()
print("Common Path:")
print("  68                   - OP_ENDIF")
print("  21 02111111...       - PUSH party1 pubkey (Alice)")
print("  21 02222222...       - PUSH party2 pubkey (Bob)")
print("  52                   - OP_2 (2 pubkeys)")
print("  ae                   - OP_CHECKMULTISIG")
print()

print("Spending scenarios:")
print()
print("Scenario A: Before timeout (ELSE branch)")
print("  ScriptSig: 0 <alice_sig> <bob_sig> 0 <script>")
print("  Stack execution:")
print("    0 <alice_sig> <bob_sig> 0  ← Initial")
print("    Evaluate IF: 0 is false → take ELSE branch")
print("    OP_2 pushed")
print("    After ENDIF: 0 <alice_sig> <bob_sig> 2")
print("    Push pubkeys: 0 <alice_sig> <bob_sig> 2 <alice_pk> <bob_pk> 2")
print("    CHECKMULTISIG: Verify 2-of-2 → true")
print()
print("Scenario B: After timeout (IF branch)")
print("  ScriptSig: 0 <alice_sig> <lenny_sig> 1 <script>")
print("  Stack execution:")
print("    0 <alice_sig> <lenny_sig> 1  ← Initial")
print("    Evaluate IF: 1 is true → take IF branch")
print("    Push locktime: 0 <alice_sig> <lenny_sig> 900000")
print("    CLTV validates (tx nLockTime >= 900000)")
print("    DROP: 0 <alice_sig> <lenny_sig>")
print("    Push escrow key: 0 <alice_sig> <lenny_sig> <lenny_pk>")
print("    CHECKSIGVERIFY: Verify lenny_sig → true, consume stack")
print("    OP_1 pushed: 0 <alice_sig> 1")
print("    After ENDIF: 0 <alice_sig> 1")
print("    Push pubkeys: 0 <alice_sig> 1 <alice_pk> <bob_pk> 2")
print("    CHECKMULTISIG: Verify 1-of-2 (alice) → true")
print()

# Show P2SH address generation
print()
print("=" * 80)
print("P2SH Address Generation")
print("-" * 80)
print()
print("For Simple Timelock Script:")
print(f"  Script (hex): {simple_script}")
print()
print("Step 1: SHA256")
import hashlib
script_bytes = bytes.fromhex(simple_script)
sha256_hash = hashlib.sha256(script_bytes).digest()
print(f"  SHA256(script) = {sha256_hash.hex()}")
print()
print("Step 2: RIPEMD160")
import hashlib
ripemd160 = hashlib.new('ripemd160')
ripemd160.update(sha256_hash)
script_hash = ripemd160.digest()
print(f"  RIPEMD160(sha256) = {script_hash.hex()}")
print()
print("Step 3: Add version byte (0x05 for P2SH)")
versioned = b'\x05' + script_hash
print(f"  Version + hash = {versioned.hex()}")
print()
print("Step 4: Calculate checksum")
checksum = hashlib.sha256(hashlib.sha256(versioned).digest()).digest()[:4]
print(f"  Checksum (first 4 bytes of double SHA256) = {checksum.hex()}")
print()
print("Step 5: Base58 encode")
import base58
address = base58.b58encode(versioned + checksum).decode('ascii')
print(f"  Final P2SH address: {address}")
print()

print("=" * 80)
print("Summary")
print("=" * 80)
print()
print("✓ Simple timelock: <locktime> CLTV DROP <pubkey> CHECKSIG")
print("✓ Escrow timelock: Complex IF/ELSE with CLTV + CHECKSIGVERIFY + CHECKMULTISIG")
print("✓ Block height: Values < 500000000")
print("✓ Timestamp: Values >= 500000000")
print("✓ Minimal encoding: Required for Bitcoin consensus")
print("✓ P2SH wrapper: Makes scripts usable with standard addresses")
print()
print("To spend these outputs, you MUST:")
print("  1. Include the full redeem script in scriptSig")
print("  2. Set transaction nLockTime >= the locktime value")
print("  3. Set input nSequence < 0xffffffff (e.g., 0xfffffffe)")
print("  4. Provide valid signature(s) for the pubkey(s)")
print()
print("⚠️  Remember: This is enforced by Bitcoin consensus rules!")
print("    Before the locktime, spending attempts will be rejected by the network.")
print()
